### ISSUE TITLE
このリポジトリとSpeakerDeckと相互リンクさせたい

### ISSUE THREAD

**Issue by takasek** [koher/async-await-challenge#1]
READMEに https://speakerdeck.com/koher/await へのリンク、
およびあちらからこのリポジトリへのリンクがあると便利だと思いました。

**Comment by takasek** [comment]
加えて、 http://swiftfiddle.com でnightlyを実行できるよという話も書いておくと、前提知識のない人がスムーズに課題にとりかかれそうです。

**Comment by koher** [comment]
@takasek ありがとうございます。

下記コミットで対応しました。

- 6b2fdfb22b03b8035d698ae4b5e90edc2ab2b574
- 96e05583400dc0697b9e7562dc51ec0201646e50

Speaker Deck から本リポジトリへのリンク、 YouTube の動画から双方へのリンクも追加済みです。

**Comment by takasek** [comment]
ありがとうございます！とてもよいと思います
